services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: chat_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/chat_app
      - PORT=3001
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./server/src:/app/src
      - ./server/prisma:/app/prisma
    command: npm run dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:3001
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    command: npm run dev
    depends_on:
      - server

volumes:
  postgres_data: